name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew fatJar
    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: hdf5-viewer.jar
        path: build/libs

